package com.vive.ondevice.risk

import com.vive.data.model.AnalyzerStatus
import com.vive.data.model.AudioQuality
import com.vive.data.model.Behavior
import com.vive.data.model.Intent
import com.vive.data.model.OodState
import com.vive.data.model.PacketRisk
import com.vive.data.model.RiskLevel
import kotlin.math.max
import kotlin.math.min

/**
 * On-device port of `backend/app/risk/fusion.py`. Same constants, same
 * noisy-OR, same guard rails, same separately-computed confidence; pinned to
 * the Python implementation by `risk_golden.json` (generated by
 * `scripts/mobile/make_risk_golden.py` from the backend code itself).
 *
 * Rules it enforces (docs/PROJECT_SPEC.md 2-3):
 *  - synthetic evidence alone cannot reach CRITICAL;
 *  - low synthetic evidence never caps risk;
 *  - missing evidence lowers CONFIDENCE, never risk;
 *  - poor audio never inflates the score.
 */
object RiskFusion {

    const val VERSION = "risk-fusion-demo-1"

    val INFLUENCE = mapOf(
        "synthetic" to 0.45, "intent" to 0.72, "behavior" to 0.45,
        "context" to 0.22, "speaker_consistency" to 0.30,
    )

    const val SYNTHETIC_ONLY_CEILING = 64

    val INTENT_RISK = mapOf(
        Intent.NORMAL_CONVERSATION to 0.05, Intent.UNKNOWN to 0.10,
        Intent.URGENT_ACTION to 0.50, Intent.CONFIDENTIAL_INFORMATION to 0.60,
        Intent.ACCOUNT_CHANGE_REQUEST to 0.65, Intent.REMOTE_ACCESS_REQUEST to 0.85,
        Intent.OTP_REQUEST to 0.92, Intent.PASSWORD_REQUEST to 0.92,
        Intent.CARD_DETAILS_REQUEST to 0.90, Intent.BANKING_CREDENTIAL_REQUEST to 0.92,
        Intent.MONEY_TRANSFER_REQUEST to 0.94, Intent.THREAT_OR_INTIMIDATION to 0.88,
    )

    val BEHAVIOR_RISK = mapOf(
        Behavior.NORMAL to 0.05, Behavior.REWARD_PROMISE to 0.45, Behavior.PRESSURE to 0.55,
        Behavior.URGENCY to 0.60, Behavior.SECRECY to 0.70, Behavior.FEAR to 0.72,
        Behavior.AUTHORITY_IMPERSONATION to 0.80, Behavior.THREAT to 0.85,
    )

    data class Input(
        val quality: AudioQuality,
        /** Null when anti-spoofing did not produce a usable score. */
        val synthetic: Double?,
        val speakerStatus: AnalyzerStatus,
        val speakerSimilarity: Double?,
        val asrStatus: AnalyzerStatus,
        val asrConfidence: Double?,
        val intentStatus: AnalyzerStatus,
        val intent: Intent,
        val behaviorStatus: AnalyzerStatus,
        val behaviors: List<Behavior>,
        val callerVerified: Boolean,
        val sessionAuthenticated: Boolean,
    )

    data class Output(
        val risk: PacketRisk,
        val quality: AudioQuality,
        val ood: OodState,
        val uncertainty: Double,
        val contextRisk: Double,
    )

    fun fuse(d: Input): Output {
        val quality = d.quality
        var contributions = linkedMapOf<String, Double>()
        var reasons = mutableListOf<String>()

        var context = 0.15
        if (!d.callerVerified) { context += 0.45; reasons += "Caller not independently verified" }
        if (!d.sessionAuthenticated) context += 0.20
        context = min(context, 1.0)
        contributions["context"] = round4(context)

        val synthetic = d.synthetic
        if (synthetic != null) {
            contributions["synthetic"] = round4(synthetic)
            if (synthetic >= 0.75) reasons += "Elevated synthetic-voice indicators"
        }

        val intentRisk = INTENT_RISK[d.intent] ?: 0.10
        if (d.intentStatus == AnalyzerStatus.AVAILABLE) {
            contributions["intent"] = round4(intentRisk)
            if (intentRisk >= 0.85) reasons += "${humanise(d.intent.name)} detected"
        }

        var behaviorRisk = 0.0
        if (d.behaviorStatus == AnalyzerStatus.AVAILABLE && d.behaviors.isNotEmpty()) {
            behaviorRisk = d.behaviors.maxOf { BEHAVIOR_RISK[it] ?: 0.3 }
            contributions["behavior"] = round4(behaviorRisk)
            d.behaviors.firstOrNull { (BEHAVIOR_RISK[it] ?: 0.0) >= 0.6 }
                ?.let { reasons += "${humanise(it.name)} in conversation" }
        }

        var speakerRisk = 0.0
        if (d.speakerStatus == AnalyzerStatus.AVAILABLE && d.speakerSimilarity != null) {
            speakerRisk = 1.0 - d.speakerSimilarity
            contributions["speaker_consistency"] = round4(d.speakerSimilarity)
        }

        val parts = linkedMapOf("context" to context)
        if (d.intentStatus == AnalyzerStatus.AVAILABLE) parts["intent"] = intentRisk
        if (synthetic != null) parts["synthetic"] = synthetic
        if (behaviorRisk != 0.0) parts["behavior"] = behaviorRisk
        if (speakerRisk != 0.0) parts["speaker_consistency"] = speakerRisk

        var survival = 1.0
        for ((k, v) in parts) survival *= 1.0 - INFLUENCE.getValue(k) * v
        var score = pyRound((1.0 - survival) * 100)

        val semanticPressure = max(parts["intent"] ?: 0.0, behaviorRisk)
        if (semanticPressure < 0.4 && score > SYNTHETIC_ONLY_CEILING) {
            score = SYNTHETIC_ONLY_CEILING
            reasons += "Synthetic indicators alone are not treated as fraud"
        }

        if (quality == AudioQuality.POOR || quality == AudioQuality.NO_SPEECH) {
            score = min(score, 15)
            reasons = mutableListOf("Insufficient clear speech to assess", "Audio quality ${quality.name}")
            val kept = contributions["context"]
            contributions = linkedMapOf<String, Double>().also { if (kept != null) it["context"] = kept }
        }

        score = score.coerceIn(0, 100)
        val (confidence, uncertainty) = confidence(d, quality, parts.size)
        return Output(
            risk = PacketRisk(
                score = score, level = levelFor(score), confidence = round4(confidence),
                contributions = contributions,
                reasons = reasons.ifEmpty { listOf("No notable risk indicators") },
            ),
            quality = quality,
            ood = ood(synthetic, quality),
            uncertainty = round4(uncertainty),
            contextRisk = round4(context),
        )
    }

    private fun confidence(d: Input, quality: AudioQuality, signals: Int): Pair<Double, Double> {
        var c = 0.55 + min(signals, 5) * 0.06
        c += when (quality) {
            AudioQuality.GOOD -> 0.15
            AudioQuality.DEGRADED -> -0.10
            else -> -0.40
        }
        if (d.asrStatus == AnalyzerStatus.AVAILABLE && d.asrConfidence != null && d.asrConfidence != 0.0) {
            c += (d.asrConfidence - 0.8) * 0.2
        }
        if (d.speakerStatus == AnalyzerStatus.NO_REFERENCE) c -= 0.05
        if (d.synthetic == null) c -= 0.15
        c = c.coerceIn(0.05, 0.97)
        return c to max(0.03, 1.0 - c)
    }

    private fun ood(synthetic: Double?, quality: AudioQuality): OodState = when {
        quality == AudioQuality.POOR || quality == AudioQuality.NO_SPEECH || synthetic == null -> OodState.UNAVAILABLE
        synthetic >= 0.75 -> OodState.KNOWN_SYNTHETIC_LIKELY
        else -> OodState.IN_DISTRIBUTION
    }

    fun levelFor(score: Int): RiskLevel = when {
        score >= 85 -> RiskLevel.CRITICAL
        score >= 65 -> RiskLevel.HIGH
        score >= 35 -> RiskLevel.MEDIUM
        else -> RiskLevel.LOW
    }

    private fun humanise(v: String) = v.replace('_', ' ').lowercase().replaceFirstChar { it.uppercase() }

    fun round4(v: Double): Double = pyRoundDigits(v, 4)

    /** Python's round(): half to even. */
    fun pyRound(v: Double): Int = Math.rint(v).toInt()

    private fun pyRoundDigits(v: Double, digits: Int): Double =
        java.math.BigDecimal(v).setScale(digits, java.math.RoundingMode.HALF_EVEN).toDouble()
}
